# haproxy configuration to proxy traffic --> ambassador:8080 --> test-svc:8081
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    frontend ambassador
      bind *:8080
      default_backend webserver-svc
    backend webserver-svc
      server svc webserver-svc:8081