# A service proxying traffic from port 80 to port 8081
apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
spec:
  selector:
    pattern: ambassador-test
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80