# A nginx webserver listening on port 80
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    pattern: ambassador-test
spec:
  containers:
  - image: nginx:stable
    name: nginx
    ports:
    - containerPort: 80