apiVersion: v1
kind: Pod
metadata:
  name: sidecar-app
spec:
  containers:
  - image: busybox:stable
    name: sidecar
    command: ['sh', '-c', 'echo "The writer wrote this" > /output/data.txt; while true; do sleep 5; done']
    volumeMounts:
    - name: shared
      mountPath: /output
  - image: busybox:stable
    name: app
    command: ['sh', '-c', 'while true; do cat /input/data.txt; sleep 5; done']
    volumeMounts:
    - name: shared
      mountPath: /input
  volumes:
  - name: shared
    emptyDir: {}