apiVersion: v1
kind: Pod
metadata:
  name: chewie
spec:
  containers:
  - name: chewie
    image: busybox
    command: [ "/bin/sh", "-c", "cat /etc/starwars/planet" ]
    volumeMounts:
    - name: kenobi-cm
      mountPath: /etc/starwars
  volumes:
  - name: kenobi-cm
    configMap:
      # Mount the config map as a file in the volume.
      # The file 'planet' contains the value 'hoth'
      name: kenobi